### ISSUE TITLE
Is adding more RFC's helpful?

### ISSUE THREAD

**Issue by kurtschelfthout** [fsharp/FSharpLangDesign#122]
Would be happy to send a few more PR's for approved uservoice items (a bit hard to see which ones still need to be added though).

Is this seen as helpful or does it just create admin overhead? If helpful, any  in particular you would like to see?

**Comment by dsyme** [comment]
It's seen as immensely useful :)

Probably best just to go through https://fslang.uservoice.com/forums/245727-f-language/status/1225914 in order of number of votes (filtered of course by your own like/dislike for the feature :) )

**Comment by kurtschelfthout** [comment]
Awesome. Thanks!
