### ISSUE TITLE
Questions on Auto-quotations design

### ISSUE THREAD

**Issue by latkin** [fsharp/FSharpLangDesign#39]
Thanks for starting to post the speclets.  A few things that I still don't quite understand for the [auto-quotations feature](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/AutoQuotation.md):

**First-class uses**
> a first-class use of the method  C.Plot  is considered shorthand for  (fun x -> C.Plot(x))  for some compiler-generated local name “x”, which will become  (fun x -> C.Plot( <@ x @> )) , so the implicit quotation will just be a local value substitution. This means a pipelines use  expr |> C.Plot  will not capture a full quotation for  expr , but rather just its value. 

Does "just ... a local value substitution" mean that the compiler-generated name is or is not captured?

**Applicability**
>The conversion only applies if the called-argument-type is type Expr for some type T, and if the caller-argument type is not of the form Expr for any U. 

What does this mean for the scenario where `T` *is* `Expr`? i.e. `static member Test([<ReflectedDefinition(true)>] values:Expr<Expr<int>>) = (...)`

Will a call to above like `Test(<@ x @>)` not compile (since caller arg is an Expr, so no transformation is done, and untransformed `Expr<int>` does not match required `Expr<Expr<int>>`?

**Overloading**
(Formatting in the first code sample here is missing, difficult to understand examples)

**Overall usefulness**
How do developers aiming to use this feature for scenario # 2 (in `Plot` function, e.g. to label axes with the text of the expression) actually do it in practice? For these scenarios (where deep structure of the quotation is not even desired), the feature is too low-level. It requires highly advanced F# knowledge to implement a robust routine to recover something even close to the original F# code that composed the expression.

If this is punted to the community, will 3rd-party implementation of some `quotationToFSharpCode` routine be brought back into the runtime, assuming it's high-quality?

I would say that with no higher-level support, this feature can only be marketed as an advanced hook for those interested in doing deep expression tree inspection/processing.  If we announce it as "enables R-like support for labeling plots!", everyone will be sorely disappointed when they realize you need expert-level chops to make that work.

**Comment by dsyme** [comment]
> Does "just ... a local value substitution" mean that the compiler-generated name is or is not captured?

Yes, the compiler-generated name is captured.  This happens with quotations already, e.g. ``<@ System.Math.Sin @>;;``

> What does this mean for the scenario where  T  is  ``Expr<_>`` ? 

No auto-quotation will apply. 

> Will 3rd-party implementation of some  quotationToFSharpCode  routine be brought back into the runtime, assuming it's high-quality?
> How do developers use this feature for scenario # 2 (in  Plot  function, e.g. to label axes with the text of the expression)

The F# language/core-library design approach for quotations is to provide some (but not necessarily all) of the building blocks to enable 3rd-party meta-programming scenarios: for example, it enables Alea.GPU, FSCL, WebSharper and LINQ queries as four examples. No particularly interesting scenarios are enabled based on FSharp.Core alone (apart from LINQ queries, and it is arguable that all the LINQ/Expression/Query support should have gone in a non-core FSharp.Linq.dll in any case, making it more like the other examples). 

So we have always designed the quotation features in the core F# language/library design to be the mincut of what's needed to enable 3rd-party scenario development by advanced F# programmers.  All four examples mentioned above are advanced frameworks that require knowledge of quotations.

So yes, I agree we shouldn't position the new feature as immediately enabling "user-oriented symbolic programming and expression display" of the kind supported by R. In this sense, the feature alone doesn't satisfy the original user-voice request - for example, more work would be needed by the providers of the F# --> R type provider (e.g. converting F# quotations to R expressions).  However the feature does address the part of the problem which can only be addressed at the languge level, which is the lack of auto-quotation and the lack of capture of local variable names.

In the particular "Plot" user scenario, the original group making the request was a team building analytics infrastructure at a financial firm.  They would be willing to put in the extra work to write a pretty-printer useful for their scenario. Likewise, the makers of FsLab would be willing to do the extra work.   Designing a general-purpose quotation --> F# code pretty printer is not particularly easy, and would need enough knobs-and-dials to work well that it needn't be in FSharp.Core.

That said, I'm definitely not opposed to having a better "quotation --> text" conversion functions in FSharp.Core. We would welcome both an Expr.Format and improvements to Expr.ToString(). Could you add an fslang.uservoice.com tracking request for both of those?

**Comment by latkin** [comment]
Ok, this all seems reasonable to me, and clarifies things. Thanks for the reply.
