### ISSUE TITLE
[RFC FS-1002 Discussion] Cartesian product for FSharp.Core Seq, List, Array

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharpLangDesign#47]
This issue is used to track discussions of [F# RFC FS-1002 - "Cartesian product for FSharp.Core Seq, List, Array"](https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1002-cartesian-product-for-collections.md). Please discuss in thread below (if necessary)

**Comment by mexx** [comment]
Do we give any guarantee about the order of the pairs?
I mean, would an implementation in reverse or random order be also acceptable for this feature?
Just asking because the current implementation PR enforces the order through the tests.

**Comment by dsyme** [comment]
Yes, the order of the pairs should be specified.  Please send a PR to the RFC to add a proposed order to match the implementation.

**Comment by jackfoxy** [comment]
I like the ordering specified in the example:

    let cross xs ys = seq { for x in xs do for y in ys -> x, y  }

I think this is the most commonly assumed ordering of [Cartesian product](https://en.wikipedia.org/wiki/Cartesian_product)

As for name, I think "cartesian" leaves no doubt about what the function does, where most of the other names leave a little room for wondering. "allPairs" would also be completely unambiguous.

**Comment by dsyme** [comment]
I think the naming should be ``allPairs``, c.f. ``Set.count`` over ``Set.cardinality``

**Comment by dsyme** [comment]
Just to note the implementation for this RFC has been submitted, using the name "allPairs".  I've marked the RFC as closed/implemented.

**Comment by dsyme** [comment]
Thanks everyone!

**Comment by abelbraaksma** [comment]
@dsyme, it appears that the RFC link in this issue description leads to a 404, could you kindly update the link to proper RFC location? May be good for historical reference (Google brought me here :))
